/**
 * Publishes the tier of every product, so something that is not BeyClub can
 * still rank a shelf.
 *
 * The grab-stock overlay runs on Kelab Gasing Beyblade's own page. It can read
 * the shop, but not the blended ranking — that is computed here from tournament
 * results, the Taiwan community sheet and the Japanese tier list, none of which
 * it can reach or reproduce. Without this file the best it could do was group
 * beys ahead of stadiums, which is not the same question as "what is worth the
 * queue place".
 *
 * The tier written here must be the tier the app shows, so this imports the
 * app's own `parseCatalogue`, `merge`, `buildStockIndex` and `gradedOn` rather
 * than reimplementing the join. It is bundled by esbuild before it runs (see
 * `npm run build:tiers`), which is what lets a Node script import the browser
 * modules' extensionless TypeScript and JSON.
 *
 * Keyed by product code, not slug: a product KGB lists after our last successful
 * scrape has no slug we know, but its code is readable from that slug, so a
 * brand-new UX-21 still resolves.
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

import { merge, parseCatalogue } from '../src/lib/loadData'
import { buildStockIndex, gradedOn, manualListings } from '../src/lib/stock'
import { tierRank } from '../src/lib/tiers'
import type { StockFile } from '../src/lib/types'

// The runner bundles this into a temp directory, so the repo cannot be found
// relative to this file at runtime — it is handed over instead.
const ROOT = process.env.BEYCLUB_ROOT
if (!ROOT) throw new Error('BEYCLUB_ROOT is unset — run this through scripts/build-product-tiers.mjs')
const DATA = join(ROOT, 'public/data')
const OUT = join(DATA, 'product-tiers.json')

const read = <T,>(name: string): T => JSON.parse(readFileSync(join(DATA, name), 'utf8')) as T

const die = (msg: string): never => {
  console.error(`✗ ${msg}`)
  process.exit(1)
}

const catalogue = read<Parameters<typeof parseCatalogue>[0]>('catalogue.json')
const tournament = read<Parameters<typeof merge>[1]>('tournament.json')
const japan = read<Parameters<typeof merge>[2]>('tiers-jp.json')
const stock = read<StockFile>('stock.json')

const parts = merge(parseCatalogue(catalogue), tournament, japan)
if (!parts.length) die('the catalogue produced no parts — refusing to publish an empty map')

// Manual listings are included so a product added by hand while the shop is shut
// still gets a tier, exactly as it does in the app.
const products = [...stock.products, ...manualListings()]
const index = buildStockIndex(products, parts)

/** Best code wins: two products can share one, and the graded part is the same. */
const byCode: Record<string, { tier: string; buy?: string }> = {}

for (const product of products) {
  if (!product.code) continue
  const best = gradedOn(index.contents(product))
  if (!best) continue

  const held = byCode[product.code]
  if (held && tierRank(held.tier) <= tierRank(best.tier)) continue
  byCode[product.code] = best.buy ? { tier: best.tier, buy: best.buy } : { tier: best.tier }
}

const graded = Object.keys(byCode).length
if (!graded) die('no product resolved to a tier — the join is broken, not the data')

writeFileSync(
  OUT,
  `${JSON.stringify(
    {
      _note:
        'Generated by scripts/build-product-tiers.ts — do not edit. Product code to blended tier, published so the grab-stock overlay can rank a shelf from KGB\'s own page, where the ranking inputs are unreachable. Deliberately carries no build timestamp: the refresh workflows commit only when a data file actually changes, and a clock in here would make every run look like a change and redeploy the site daily for nothing.',
      tiers: byCode,
    },
    null,
    2,
  )}\n`,
)

console.log(`✓ ${graded} product codes graded → public/data/product-tiers.json`)
